### PR TITLE
Add Support for Multiple Announce URIs

### PR DESCRIPTION
**Pull request by martindale**
As per BEP 0012, `announce-list` should override `announce` and allow for multiple trackers per torrent.  This implements that BEP.

### CODE REVIEW

**Comment by unusualbob** [comment]
Will accept if strings are converted back to double quotes. Y u change my formatting.

**Comment by martindale** [comment]
Add a `CONTRIBUTING.md` if you want something that differs from [the common conventions](https://github.com/felixge/node-style-guide)!  Also, a hint file would be good for future contributions.  I try to adhere to Felix's style guide, but will comply if something else is provided.

**Comment by unusualbob** [comment]
Added one minute before your comment :P 
https://github.com/unusualbob/node-torrent-stream/blob/master/contributing.md

**Comment by martindale** [comment]
double quotes?  eww.

fixed!

**Comment by unusualbob** [comment]
When testing this I noticed it fails if you do not pass the trackers option. Recommend modifying the way you add trackers to metadata.

```
var metadata = {
    announce: self.announce,
    "creation date": parseInt(Date.now() / 1000),
    info: self.info
  };

if (self.trackers) {
  metadata["announce-list"] = [self.trackers];
}
```

This should work

**Comment by unusualbob** [comment]
Actually, shouldn't `trackers` already be an array of arrays? If thats the case I don't know why we'd be making it an additional array level deep. Should be something like: `trackers: [["tracker1"],["tracker2"]];` in the initial options. So that finally we do `metadata["announce-list"] = self.trackers;`

**Comment by unusualbob** [comment]
Well since this has been a few days and I had some time, I went ahead and fully implemented this, along with tests etc. Let me know if anything seems off.

**Pull request closed without merging**
